### PR TITLE
Python3 pickle friendly

### PR DESCRIPTION
**Pull request by exowanderer**
Python2 pickle formats write as bytestrings, but Python3 reads them as strings. To read a Python2 pickle in Python3, we must first read in the file as 'rb'. such as 

`pkl.load(filename, 'rb')`

and store them as 

`pkl.dump(filename, 'wb')`

In the reading case -- not an issue here -- we must set the pickle encoding as 'latin1' for it to read/write between Python2 and Python3. I got all of this information from

http://stackoverflow.com/questions/28218466/unpickling-a-python-2-object-with-python-3

------
In addition, in the file "hst.py" there was a `pandas` command that converted a DataFrame to html (`.to_html()`) and then 'encoded' it (`.encode()`).  

In Python3, the encoding line

`input_div = pd.DataFrame(input_dict.items(), columns=['Component', 'Values']).to_html()#.encode()`

converts the string to a bytestring, which then flags an error on the line below

`input_div = '<table class="table table-striped"> \n' + input_div[36:len(input_div)]`

because Python3 cannot concatenate strings with bytestrings.  To avoid this, I commented out the `.encode()` section on line 571, which cleared the error and I was able to continue with the tutorial notebook "HST_WFC3.ipynb"

------
Because both issues involve and "encoding", I would imagine that they are the same underlying Python2 vs Python3 issue; but the application is vastly different. Either way, this PR allows the "HST_WFC3.ipynb" tutorial notebook to operate smoothy with Python3

### CODE REVIEW

**Comment by natashabatalha** [comment]
Ah, interesting. You are going to encounter the same issue in jwst.py (line 820). If you do that while using the online UI (run_online), what do your tables look like? They should something like this: 

screen shot 2017-03-13 at 12 58 08 pm

**Comment by exowanderer** [comment]
I get a completely different issue when I use the JWST_Running_Pandexo.ipynb tutorial.  

Apparently, in `telescope.py: line 12` generates a `None`.  This of course propagates down to `line 33`

`self.ref_dir = os.path.join(default_refdata_directory, self.tel_name, "telescope")`

which cannot concatenate a `None` with a `string` inside the `.join()` function.

**Comment by natashabatalha** [comment]
That looks like a path issue. Did you do download the Pandeia reference data and export the path?? 

https://natashabatalha.github.io/PandExo/installation.html

**Comment by exowanderer** [comment]
I don't think that I have the appropriate setup to answer your question.  I am not "running it online". I have only tested accessing PandExo via the tutorial notebooks. 

Could you explain how to use `run_online.py` or just how to generate the table that you want me to compare with?

Please

**Comment by natashabatalha** [comment]
Oh oh sorry. If you just open python in the terminal run: 

`import pandexo.engine.run_online as ro`
`ro.main()`

Then go to whatever you use as an internet browser and go to "http://localhost:1111"

It will create the webpage locally on your machine. So then if you go to JWST -> New Calculation. Run a simulation, and proceed to the output page, you should see a pretty table like the one above.

**Comment by exowanderer** [comment]
I got pandas .... not the package, the animal

**Comment by natashabatalha** [comment]
Hahaha. That's what I figured. I'll figure something out to fix this asap.

**Comment by exowanderer** [comment]
Oh. I forgot that Jupyter outputs tracebacks too:

```
    Traceback (most recent call last):
      File "/Users/jfraine/anaconda3/lib/python3.6/site-packages/tornado/web.py", line 1467, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/Users/jfraine/anaconda3/lib/python3.6/site-packages/pandexo.engine-0.0.dev7-py3.6.egg/pandexo/engine/run_online.py", line 286, in post
        fh_plan.write(fileinfo_plan['body'])
    TypeError: write() argument must be str, not bytes
```

This should be fixable by using 

```
fh_plan.write(fileinfo_plan['body'], 'wb')
```

or the equivalent for this `.write()` package.

**Comment by exowanderer** [comment]
That pushed the pandas forward by one screen.  Now I get to a screen that says it's running the operation. Then it "finished" and finally, if I click the "eye" on this screen, I get pandas with traceback that I attached below. 

This gist seems to be `telescope.py` wants to append the $PATH though `os` with a NoneType.  This is similar to what I found with the `cf.default_refdata_directory` error above.

screen shot 2017-03-13 at 4 07 31 pm

```
    Traceback (most recent call last):
      File "/Users/jfraine/anaconda3/lib/python3.6/site-packages/pandexo.engine-0.0.dev7-py3.6.egg/pandexo/engine/jwst.py", line 70, in compute_full_sim
        i = InstrumentFactory(config=conf)
      File "/Users/jfraine/anaconda3/lib/python3.6/site-packages/pandeia.engine-1.0-py3.6.egg/pandeia/engine/instrument_factory.py", line 51, in InstrumentFactory
        cls = inst_map[instrument](mode=mode, config=config, webapp=webapp, **kwargs)
      File "/Users/jfraine/anaconda3/lib/python3.6/site-packages/pandeia.engine-1.0-py3.6.egg/pandeia/engine/jwst.py", line 56, in __init__
        JWSTInstrument.__init__(self, mode=mode, config=config, webapp=webapp, **kwargs)
      File "/Users/jfraine/anaconda3/lib/python3.6/site-packages/pandeia.engine-1.0-py3.6.egg/pandeia/engine/jwst.py", line 34, in __init__
        telescope = JWST()
      File "/Users/jfraine/anaconda3/lib/python3.6/site-packages/pandeia.engine-1.0-py3.6.egg/pandeia/engine/config.py", line 46, in __init__
        self.__dict__.update(merge_data(self._get_config(), config, dict(**kwargs)))
      File "/Users/jfraine/anaconda3/lib/python3.6/site-packages/pandeia.engine-1.0-py3.6.egg/pandeia/engine/telescope.py", line 33, in _get_config
        self.ref_dir = os.path.join(default_refdata_directory, self.tel_name, "telescope")
      File "/Users/jfraine/anaconda3/lib/python3.6/posixpath.py", line 78, in join
        a = os.fspath(a)
    TypeError: expected str, bytes or os.PathLike object, not NoneType
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/Users/jfraine/anaconda3/lib/python3.6/concurrent/futures/process.py", line 175, in _process_worker
        r = call_item.fn(*call_item.args, **call_item.kwargs)
      File "/Users/jfraine/anaconda3/lib/python3.6/site-packages/pandexo.engine-0.0.dev7-py3.6.egg/pandexo/engine/pandexo.py", line 33, in wrapper
        return compute_full_sim(dictinput)
      File "/Users/jfraine/anaconda3/lib/python3.6/site-packages/pandexo.engine-0.0.dev7-py3.6.egg/pandexo/engine/jwst.py", line 76, in compute_full_sim
        i = InstrumentFactory(config=conf_temp)
      File "/Users/jfraine/anaconda3/lib/python3.6/site-packages/pandeia.engine-1.0-py3.6.egg/pandeia/engine/instrument_factory.py", line 51, in InstrumentFactory
        cls = inst_map[instrument](mode=mode, config=config, webapp=webapp, **kwargs)
      File "/Users/jfraine/anaconda3/lib/python3.6/site-packages/pandeia.engine-1.0-py3.6.egg/pandeia/engine/jwst.py", line 56, in __init__
        JWSTInstrument.__init__(self, mode=mode, config=config, webapp=webapp, **kwargs)
      File "/Users/jfraine/anaconda3/lib/python3.6/site-packages/pandeia.engine-1.0-py3.6.egg/pandeia/engine/jwst.py", line 34, in __init__
        telescope = JWST()
      File "/Users/jfraine/anaconda3/lib/python3.6/site-packages/pandeia.engine-1.0-py3.6.egg/pandeia/engine/config.py", line 46, in __init__
        self.__dict__.update(merge_data(self._get_config(), config, dict(**kwargs)))
      File "/Users/jfraine/anaconda3/lib/python3.6/site-packages/pandeia.engine-1.0-py3.6.egg/pandeia/engine/telescope.py", line 33, in _get_config
        self.ref_dir = os.path.join(default_refdata_directory, self.tel_name, "telescope")
      File "/Users/jfraine/anaconda3/lib/python3.6/posixpath.py", line 78, in join
        a = os.fspath(a)
    TypeError: expected str, bytes or os.PathLike object, not NoneType
    """
    
    The above exception was the direct cause of the following exception:
    
    Traceback (most recent call last):
      File "/Users/jfraine/anaconda3/lib/python3.6/site-packages/tornado/web.py", line 1467, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/Users/jfraine/anaconda3/lib/python3.6/site-packages/pandexo.engine-0.0.dev7-py3.6.egg/pandexo/engine/run_online.py", line 733, in get
        result = self._get_task_result(id)
      File "/Users/jfraine/anaconda3/lib/python3.6/site-packages/pandexo.engine-0.0.dev7-py3.6.egg/pandexo/engine/run_online.py", line 171, in _get_task_result
        return task.result()
      File "/Users/jfraine/anaconda3/lib/python3.6/concurrent/futures/_base.py", line 398, in result
        return self.__get_result()
      File "/Users/jfraine/anaconda3/lib/python3.6/concurrent/futures/_base.py", line 357, in __get_result
        raise self._exception
      File "/Users/jfraine/anaconda3/lib/python3.6/site-packages/tornado/web.py", line 1467, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/Users/jfraine/anaconda3/lib/python3.6/site-packages/pandexo.engine-0.0.dev7-py3.6.egg/pandexo/engine/run_online.py", line 733, in get
        result = self._get_task_result(id)
      File "/Users/jfraine/anaconda3/lib/python3.6/site-packages/pandexo.engine-0.0.dev7-py3.6.egg/pandexo/engine/run_online.py", line 171, in _get_task_result
        return task.result()
      File "/Users/jfraine/anaconda3/lib/python3.6/concurrent/futures/_base.py", line 398, in result
        return self.__get_result()
      File "/Users/jfraine/anaconda3/lib/python3.6/concurrent/futures/_base.py", line 357, in __get_result
        raise self._exception
    TypeError: expected str, bytes or os.PathLike object, not NoneType
```

**Comment by natashabatalha** [comment]
Sorry it took so long but PandExo is now fully Python 3.6 compatible (and 2.7 back compatible)

**Comment by exowanderer** [comment]
Excellent! I'll go play with it!

**Pull request closed without merging**
