### PR TITLE
Adding Order 2 PandExo Output for NIRISS SOSS Mode Observations

### PR DESCRIPTION
**Pull request by mfixstsci**

### CODE REVIEW

**Comment by natashabatalha** [comment]
Quick thoughts: 

- One annoying piece of this development will be handing the bokeh js callbacks in run_online. Right now there is this old javascript code to do the binning that will not know what to do with regions of order 1/2 overlap. The easiest way to handle it would be to pre-build one dictionary output with both orders that has an ordered, non overlapping axis. It might not directly capture how binning would be done IRL but it would be easiest to manage. 
- It would be helpful if the python API and runonline had similar behavior. Again, this maps to my comment above about making edits outside of run_online and instead just change how jwst.py operates when a NIRISS SOSS run is requested. I recommend that the final data products that are used (e.g. things located in FinalSpectrumOutput) be an aggregation of o1 and o2. Then, create other products that break down order 1 and order 2 for people that want it. This would introduce nearly no changes to a users workflow. 
- The change to the user via python interface is that this: `result = jdi.run_pandexo(exo_dict,['NIRISS SOSS'])` would trigger both O1 and O2 (longer run time). 
- [This tutorial](https://natashabatalha.github.io/PandExo/tutorialjwst.html#running-niriss-soss-order-2) would be changed to something like "Run only NIRISS order 1 or only order 2". It would explain that this forces "optimize" group to occur on either order 2, or order 1, and produce shorter run times (if users dont care about doing both).

**Comment by mfixstsci** [comment]
@natashabatalha sounds good to me. I can make sure to remove the changes in `run_online` and just update `jwst.py`. I notice that the change I made to `run_online` would only produce the order two spectra and not both if we set the group to "optimize". I am thinking that we offer the ability to run `1, 2 , "both"` to be more transparent with our users and whats going on under the hood. I was able to use the example you sent me and got everything up and running just fine for order 1. But now I am experiencing some issues with changing the order to 2

`DataError: No mask configured for SOSS order 2.`

```
{'telescope': 'jwst',
 'scene': [{'id': 1,
   'target': True,
   'position': {'ang_unit': 'arcsec', 'x_offset': 0.0, 'y_offset': 0.0},
   'shape': {'geometry': 'point'},
   'spectrum': {'extinction': {'bandpass': 'j',
     'law': 'mw_rv_31',
     'unit': 'mag',
     'value': 0.0},
    'normalization': {'type': 'none'},
    'sed': {'sed_type': 'input',
     'spectrum': array([[5.00010000e-01, 5.00160000e-01, 5.00310000e-01, ...,
             1.49900300e+01, 1.49944800e+01, 1.49989300e+01],
            [6.69523848e+02, 6.01890516e+02, 3.98278725e+02, ...,
             1.66916936e+01, 1.66826677e+01, 1.66644470e+01]])},
    'lines': []}}],
 'background_level': 'medium',
 'background': 'ecliptic',
 'calculation': {'effects': {'background': True,
   'ipc': True,
   'saturation': True},
  'noise': {'crs': True,
   'darkcurrent': True,
   'ffnoise': False,
   'readnoise': True,
   'rn_correlation': True}},
 'configuration': {'instrument': {'instrument': 'niriss',
   'mode': 'soss',
   'filter': 'clear',
   'aperture': 'soss',
   'disperser': 'gr700xd'},
  'detector': {'readout_pattern': 'nisrapid',
   'subarray': 'substrip96',
   'readmode': 'nisrapid',
   'ngroup': 2,
   'nint': 1,
   'nexp': 1}},
 'strategy': {'method': 'soss', 'order': 2, 'background_subtraction': False}}
```

Once we have both results, combining them should be easy to do from there.

**Comment by mfixstsci** [comment]
@natashabatalha I was able to update the instrument dict and got order 2 working. I will let you know what comes from combining the spectra!

**Comment by mfixstsci** [comment]
@nespinoza Here are the changes to the app to allow users to select the order when using `NIRISS Substrip256`.

**Comment by hover2pi** [comment]
Trying to run this locally, there are a few issues I ran into. I'm not sure which Python versions are supported but 3.10 has issues with the relative imports in the `run_online.py` module. And if I run it in Python v3.7, I get import errors with the `wrapper.py` module complaining about the `main()` function. Is this a can of worms I shouldn't be opening?

**Comment by nespinoza** [comment]
Hey @hover2pi --- did you try running first the `run_test.py` to check everything installed correctly? (if not, see https://github.com/natashabatalha/PandExo/issues/59).

**Comment by hover2pi** [comment]
Yes, `run_test.py` works fine but I am not able to run the server on localhost to check the fields. I get the error about relative imports:
```
Traceback (most recent call last):
  File "/Users/jfilippazzo/Documents/Modules/PandExo/pandexo/engine/run_online.py", line 23, in <module>
    from .pandexo import wrapper
ImportError: attempted relative import with no known parent package
```
If I change the relative imports to absolute imports it works but these edits don't seem to be in the PR. Advice?

Here's my env:
```
# Name                    Version                   Build  Channel
astropy                   6.0.1                    pypi_0    pypi
astropy-iers-data         0.2024.7.29.0.32.7          pypi_0    pypi
astroquery                0.4.7                    pypi_0    pypi
backports-tarfile         1.2.0                    pypi_0    pypi
batman-package            2.4.9                    pypi_0    pypi
beautifulsoup4            4.12.3                   pypi_0    pypi
bokeh                     3.0.2                    pypi_0    pypi
bzip2                     1.0.8                hfdf4475_7    conda-forge
ca-certificates           2024.7.4             h8857fd0_0    conda-forge
certifi                   2024.7.4                 pypi_0    pypi
charset-normalizer        3.3.2                    pypi_0    pypi
contourpy                 1.2.1                    pypi_0    pypi
greenlet                  3.0.3                    pypi_0    pypi
html5lib                  1.1                      pypi_0    pypi
idna                      3.7                      pypi_0    pypi
importlib-metadata        8.2.0                    pypi_0    pypi
jaraco-classes            3.4.0                    pypi_0    pypi
jaraco-context            5.3.0                    pypi_0    pypi
jaraco-functools          4.0.1                    pypi_0    pypi
jinja2                    3.1.4                    pypi_0    pypi
joblib                    1.4.2                    pypi_0    pypi
keyring                   25.2.1                   pypi_0    pypi
libffi                    3.4.2                h0d85af4_5    conda-forge
libsqlite                 3.46.0               h1b8f9f3_0    conda-forge
libzlib                   1.3.1                h87427d6_1    conda-forge
markupsafe                2.1.5                    pypi_0    pypi
more-itertools            10.3.0                   pypi_0    pypi
ncurses                   6.5                  h5846eda_0    conda-forge
numpy                     1.26.4                   pypi_0    pypi
openssl                   3.3.1                h87427d6_2    conda-forge
packaging                 24.1                     pypi_0    pypi
pandas                    2.2.2                    pypi_0    pypi
pandeia-engine            3.0                      pypi_0    pypi
photutils                 1.11.0                   pypi_0    pypi
pillow                    10.4.0                   pypi_0    pypi
pip                       24.1.2             pyhd8ed1ab_0    conda-forge
pyerfa                    2.0.1.4                  pypi_0    pypi
pysynphot                 2.0.0                    pypi_0    pypi
python                    3.9.19          h7a9c478_0_cpython    conda-forge
python-dateutil           2.9.0.post0              pypi_0    pypi
pytz                      2024.1                   pypi_0    pypi
pyvo                      1.5.2                    pypi_0    pypi
pyyaml                    6.0.1                    pypi_0    pypi
readline                  8.2                  h9e318b2_1    conda-forge
requests                  2.32.3                   pypi_0    pypi
scipy                     1.13.1                   pypi_0    pypi
setuptools                72.1.0                   pypi_0    pypi
six                       1.16.0                   pypi_0    pypi
soupsieve                 2.5                      pypi_0    pypi
sqlalchemy                2.0.31                   pypi_0    pypi
stsynphot                 1.3.0                    pypi_0    pypi
synphot                   1.3.post0                pypi_0    pypi
tk                        8.6.13               h1abcd95_1    conda-forge
tornado                   6.4.1                    pypi_0    pypi
typing-extensions         4.12.2                   pypi_0    pypi
tzdata                    2024.1                   pypi_0    pypi
urllib3                   2.2.2                    pypi_0    pypi
webencodings              0.5.1                    pypi_0    pypi
xyzservices               2024.6.0                 pypi_0    pypi
xz                        5.2.6                h775f41a_0    conda-forge
zipp                      3.19.2                   pypi_0    pypi
```

**Comment by natashabatalha** [comment]
@hover2pi Python 3.7 is not supported. I can't replicate your parent package issue with Py 3.11.9. I did encounter an issue with numpy=>2.0 but that doesnt seem to be your problem. I tested this on the local web app and it seems to be all good. How are you trying to run the local server?

**Pull request merged**
