### PR TITLE
Implementing edit, validation, text outputs, saturation plots, bug fixes

### PR DESCRIPTION
**Pull request by ideasrule**
The changes were made to both the JWST and HST workflows, unless otherwise stated.  Working demo [here](http://linelists.caltech.edu:1111/).

New features:

1. The "edit" functionality works now.  The user can now easily change one parameter and re-run the calculation.  Files to upload have to be re-selected because Javascript security features forbid uploading files without explicit user consent.
2. Pretty much every field of the form is now validated before submission.  Instead of letting the user submit and then crashing, forcing the user to fill out the whole form from scratch, it refuses to submit
3. Added "Edit Calculation" and "Dashboard" buttons to the View page for easy navigation
4. Added "New Calculation" button to Dashboard for convenience
5. "View" page now allows user to download the simulated observations + errors in text format
6. JWST View page now shows number of partially and fully saturated pixels vs. wavelength, allowing user to know which wavelengths are saturated
7. Default values now populated for many text fields and dropdown lists, partially because they're common choices, partially to make it impossible to submit without choosing a dropdown option

Bug fixes:

1. The temperatures in the Fortney grid are now sorted
2. The form is no longer reset when user resolves a target name
3. Files are now closed after being opened

Technical improvements:
1. To simplify the code, enable easier validation, and prevent form resetting, the "Resolve Target" button no longer submits the form.  It instead does a GET request to an independent handler.
2. Reduced code duplication in calc_row.html and calc_rowhst.html

### CODE REVIEW

**Comment by natashabatalha** [comment]
These are awesome changes @ideasrule 

Thanks so much for your contribution. We need sometime to test this on the ST server before implementation. We will keep you posted.

**Comment by nespinoza** [comment]
Testing has begun at Space Telescope; @mfixstsci is leading the effort, I'll be supporting him. Will report over here on what we find!

**Comment by ideasrule** [comment]
@mfixstsci Sure, here are the updated fields.  The defaults aren't necessary, so if they pose problems, I can remove them.  But all the defaults are defined in the HTML files, so they shouldn't affect the backend at all.

HST only: 

1. "WFC3" is now the default instrument.  "STIS" is disabled in the dropdown list.

JWST only:

1. "Get Default from Phoenix" is the default stellar model
2. 80 is the default saturation value
3. Slitless LRS is default if user selects MIRI
4. G395H and sub2048 are defaults if user selects NIRSPEC
5. F322W2 and SUBGRISM64 are defaults if user selects NIRCam
6. Substrip256 is default if user selects NIRISS

Both HST and JWST: 

1. "constant value" is the default planet model

**Comment by mfixstsci** [comment]
> @mfixstsci Sure, here are the updated fields. The defaults aren't necessary, so if they pose problems, I can remove them. But all the defaults are defined in the HTML files, so they shouldn't affect the backend at all.
> 
> HST only:
> 
>     1. "WFC3" is now the default instrument.  "STIS" is disabled in the dropdown list.
> 
> 
> JWST only:
> 
>     1. "Get Default from Phoenix" is the default stellar model
> 
>     2. 80 is the default saturation value
> 
>     3. Slitless LRS is default if user selects MIRI
> 
>     4. G395H and sub2048 are defaults if user selects NIRSPEC
> 
>     5. F322W2 and SUBGRISM64 are defaults if user selects NIRCam
> 
>     6. Substrip256 is default if user selects NIRISS
> 
> 
> Both HST and JWST:
> 
>     1. "constant value" is the default planet model

Awesome @ideasrule thank you! I found out that the I was using an old version of the `pandeia_data` so that was causing the crash 🙄 I am going to look at the default fields you mentioned and at that point will be done testing. Thanks again!

**Comment by mfixstsci** [comment]
@nespinoza I went ahead and verified the new features locally. I am going to go ahead and pull this branch down on the ExoCTK test server. I also want to mention here, STScI is no longer supporting python 3.8 so I am currently using python 3.9 to test these changes.

**Comment by nespinoza** [comment]
Hi @ideasrule,

 Thanks again for these changes! **We're having troubles (i.e., tests are failing) handling the upgrade on the "Resolve Target" button**, i.e., this "upgrade":
 
`To simplify the code, enable easier validation, and prevent form resetting, the "Resolve Target" button no longer submits the form. It instead does a GET request to an independent handler.`

 This is most definitely not working on the ST servers in our tests. The exact cause is unknown so far, but the ST servers do have extra security measures embedded into them which we need to circumvent sometimes to comply with them. This includes restricting some communication between code, and that might very well be the case/problem in this case. Even if this button change was reverted, however, the form validation that you implemented, although nice, is incompatible with the way in which the "Resolve Target" button worked before your changes --- because that performed an actual form submission (to get the planet data).

 The reality of things at this stage is that our resources are limited right now to fix this. **On top of this, we're against the clock because JWST Cycle 3 is already underway**. I thus, see two ways forward:

1. We hold off on merging this PR as it is until after the JWST Cycle 3 deadline to figure this out with more time in our hands. 
2. @ideasrule reverts some of the updates on this PR, we work on testing & merging the rest, and leave the particular "Resolve Target" button and form validation upgrades for after the JWST Cycle 3 deadline. **This will need to happen, hopefully, before the end of next week**.

 If @ideasrule would be happy with Option number 2 above, my suggestion on how to proceed would be to do the following:
  
- [ ] 1. Task for @ideasrule: **Roll back both the form validation and the "Resolve Target" button to its previous state in this PR** (i.e., with the "Resolve Target" button having the embedded dictionary definitions in the HTML code).
- [ ] 2. Task for @ideasrule: test locally that it works. Let us know when this PR is updated with those changes via the comments here.
- [ ] 3. Task for @mfixstsci: test that the updated PR works on the ST servers.
- [ ] 4. Task for @natashabatalha: merge this updated PR to `master` (i.e., approve and merge this PR).

 Optional tasks for @ideasrule: 

- [ ] Wait for the next PandExo release that @natashabatalha will implement shortly for PandExo to be in line with pandeia.
- [ ] Once that release is done and tested by us at ST, and merged to master, submit a PR on top of that release with this button change.

 With that, we can then proceed to test this button change and form validation in our servers and get that implemented after the JWST Cycle 3 deadline.
 
  @ideasrule --- please let me know what you think. 

 Thanks,
Néstor

**Comment by ideasrule** [comment]
@nespinoza One possibility is that for some reason, the servers are rejecting GET requests made by jQuery and only accepting POST requests.  I've just changed the GET to a POST.  Can you try testing it again?

**Comment by mfixstsci** [comment]
@ideasrule thank you for making the change. I was able to pull them down and kick the server back off but the resolve target button is still not triggering an event. 

As for the edit, thank you for letting us know about this issue. I wonder if we were able to get the changes in this PR up and running if it would show the same behavior.

**Comment by nespinoza** [comment]
Hi folks, unless there is another idea to solve these issues (which, I understand: hard to debug) --- I propose we follow solutions 1 or 2 above. Any takes on that @ideasrule?

Again, thanks so much --- and sorry this turned out to be a bit harder to make work than expected.

N.

**Comment by ideasrule** [comment]
> Hi folks, unless there is another idea to solve these issues (which, I understand: hard to debug) --- I propose we follow solutions 1 or 2 above. Any takes on that @ideasrule?

Just to be sure, you're trying the resolve button on the JWST "New Calculation" page and not the HST page?

When you do start_pandexo on the server, it should start logging requests to the terminal.  Can you send me the output that appears when the user clicks the "Resolve Target" button?

On the browser side, I've also added some code that throws three popup dialogs (alerts) if the resolve fails.  Can you send me the content of these dialogs?

It would be even better if you could give me the URL of the STScI test server, so that I can try sending requests to it and seeing why they fail.

**Comment by nespinoza** [comment]
Hi @ideasrule, 

 Yes, we're checking on JWST.

 We log everything because the service doesn't run in the usual terminal --- it's a service bundle we get from IT. We do output everything to a log file, but nothing gets logged there when pressing the button.
 
 I sadly can't give you access to the test server, as this is only for internal staff.

 I'm very sorry this doesn't sound as positive and straightforward as it should --- but I would once again like to suggest we either (1) skip this upgrade now or (2) changes are made to the PR, we test that and then merge it to production. Thoughts @natashabatalha?

 Thanks,
Néstor

**Comment by ideasrule** [comment]
@nespinoza  @mfixstsci Great, with the diagnostic information, I'm pretty sure I know what the problem is.  The Javascript was POSTing to an absolute path rather than a relative one.  So if your endpoint is at http://something.org/pandexo, as I suspect it is, then it was trying to access http://something.org/resolve instead of http://something.org/pandexo/resolve.

I just pushed a change to fix the problem.  I'm pretty sure it should work now.  Could you try again?  If it works, I'll make a final commit to strip out the testing code, revert the POST back to a GET, and implement the changes on the HST side.

**Comment by ideasrule** [comment]
> @ideasrule thank you for your work on this! I have some good news! The form population is working as expected on the test server now! @nespinoza would you like to give it a go to verify?

Glad to hear it!  I made a final commit, which changed the POST back to a GET because it's easier to understand and debug.  I also fixed the URL on the HST side.  Finally, I added the debugging prompts on the HST side while keeping those on the JWST side, so that if the resolve ever fails, the user can report the error message instead of just saying it failed.

Hopefully this should be my last commit.  Let me know if any other problems arise.

**Comment by mfixstsci** [comment]
> > @ideasrule thank you for your work on this! I have some good news! The form population is working as expected on the test server now! @nespinoza would you like to give it a go to verify?
> 
> Glad to hear it! I made a final commit, which changed the POST back to a GET because it's easier to understand and debug. I also applied the URL change to the HST side. Finally, I added the debugging prompts on the HST side while keeping those on the JWST side, so that if the resolve ever fails, the user can report the error message instead of just saying it failed.
> 
> Hopefully this should be my last commit. Let me know if any other problems arise.

Sounds great! I will go ahead and set up the latest commit on the test server now. We are going to test the HST side later this afternoon and will reach back out to you soon!

**Comment by mfixstsci** [comment]
@ideasrule I just pulled your most recent commit and installed it on the server and everything on the JWST side looks great!

**Pull request merged**
