### PR TITLE
need to set workers in main loop

### PR DESCRIPTION
**Pull request by mattjhill**
Sorry, I missed this in #14 .

### CODE REVIEW

**Comment by natashabatalha** [comment]
I've just been merging all your commits but I should probably ask how you are testing these?

**Comment by mattjhill** [comment]
On the server

**Comment by natashabatalha** [comment]
Got it. When you implemented the parallel runs did you test out 4 simultaneous runs of various memory usage? Or were those parallel runs limited by memory usage as well?

**Comment by mattjhill** [comment]
I've been submitting multiple jobs with SOSS SUBSTRIP256.  If you try to run 4 at once you get a `MemoryError` on the most recent 2 jobs but then you also get a `BrokenProcessPool` on the others.  This error persists for all subsequent jobs and basically makes the service unusable and requires a restart server-side to get it back.  

I have max_workers=2 on the server.  This isn't the most resource efficient setup since even less memory intensive jobs that could in theory run safely will have to wait for the 2 jobs ahead to finish but it should be safe against a `BrokenProcessPool`.

**Comment by natashabatalha** [comment]
We know how much memory each instrument run should take. Is there a way to update max_workers right before each submit based on what is currently running and how much memory is left over ?

**Comment by natashabatalha** [comment]
Or maybe we just implement queuing ??  
http://www.tornadoweb.org/en/stable/queues.html

**Comment by mattjhill** [comment]
The `ProcessPoolExecutor` already has an internal `Queue` (looks like @nmearl [already thought about this 2 years ago](https://stackoverflow.com/questions/33553940/queue-and-processpoolexecutor-in-tornado))

If you want to maximize concurrent jobs you would have to implement something by hand like you suggested.  Add more info about the calculation type to the `CalculationTask`, check the `buffer` to see what tasks are currently running, check how much memory would be used with the new task and either add it or wait for something to finish.  

You can access the `ProcessPoolExecutor._max_workers`, so you also might be able to bump it up before you submit a job if you do the memory check and see that's there's enough available, but I'm not sure if changing it on the fly would have unintended consequences on the existing `Queue`.

**Pull request merged**
